name: PHP Syntax Check

on:
  push:
    branches:
      - main # Or master, depending on your branch

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHP Syntax Check
        run: |
          find . -name "*.php" -print0 | xargs -0 -n 1 php -l
